Repository RedHatInsights/registration-assistant, pull requests merged in 2020-08, with the labels that each got.

#7 Adds Register with RHUI/Public Cloud path
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/App.js
  src/Messages.js
  src/Routes/Register/Helpers.js
  src/Routes/Register/Helpers.scss
  src/Routes/Register/Register.js
  src/entry-dev.js
Labels: :beers:, enhancement

#6 Add Register with RHSM - ansible path
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/App.scss
  src/Components/AnsibleTabs/AnsibleTabs.js
  src/Components/AnsibleTabs/AnsibleTabs.scss
  src/Messages.js
  src/Routes/Register/Helpers.js
  src/Routes/Register/Helpers.scss
  src/Routes/Register/Register.js
  src/Routes/Register/Register.scss
Labels: :taco:, enhancement

#8 Make style changes
  src/App.scss
  src/Components/AnsibleTabs/AnsibleTabs.scss
  src/Routes/Register/Register.scss
Labels: :taco:, bug

#9 Ensure consistent split backgrond-color
  src/App.scss
  src/Components/AnsibleTabs/AnsibleTabs.scss
  src/Routes/Register/Register.scss
Labels: bug

#10 Make right side scrollable
  src/Components/AnsibleTabs/AnsibleTabs.scss
  src/Routes/Register/Register.scss
Labels: :beers:, bug

#12 Update readme
  README.md
Labels: :taco:

#13 feat(drawer-and-comps): added drawer and supporting components
  src/App.scss
  src/Components/AnsibleTabs/AnsibleTabs.js
  src/Components/AnsibleTabs/AnsibleTabs.scss
  src/Components/Group/Group.js
  src/Components/Group/Group.scss
  src/Routes/Register/Helpers.js
  src/Routes/Register/Helpers.scss
  src/Routes/Register/Register.js
  src/Routes/Register/Register.scss
Labels: :soap: :socks: :honey_pot: :nail_care: :waffle:, enhancement

#14 Hook up Accordion component
  src/Components/AnsibleTabs/AnsibleTabs.js
  src/Components/AnsibleTabs/AnsibleTabs.scss
Labels: :taco:, enhancement

#15 Sort imports, update deps/translations
  .gitignore
  locales/data.json
  locales/translations.json
  package-lock.json
  package.json
  src/Components/Group/Group.js
  src/Components/Loading/Loading.js
  src/Routes/Register/Helpers.js
  src/Routes/Register/Register.js
Labels: :beers:, tech debt

#16 Add Clipboard component
  src/App.scss
  src/Components/AnsibleTabs/AnsibleTabs.js
  src/Components/Group/Group.scss
  src/Routes/Register/Helpers.js
  src/Routes/Register/Register.scss
Labels: :beers:, enhancement

#17 Big cleanup, 🙅‍♂️ term lead code, 🙅🏾‍♀️ form initial values, orderly section reveal
  .gitignore
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  package-lock.json
  package.json
  sitemap.xml
  src/App.js
  src/Components/AnsibleTabs/AnsibleTabs.js
  src/Messages.js
  src/Routes/Register/Helpers.js
  src/Routes/Register/Register.js
  src/Utilities/Api.js
  src/Utilities/Debounce.js
  src/entry-dev.js
  src/entry.js
  src/store/index.js
Labels: :taco:, enhancement, tech debt

#19 Updates deps
  package-lock.json
  package.json
  sitemap.xml
Labels: tech debt
