Repository RedHatInsights/registration-assistant, pull requests merged in 2021-04, with the labels that each got.

#30 Adds 8.4 os support, swaps os n systems managed queries 🤙🏾🥑
  .eslintrc.yml
  build/messages/src/Messages.json
  config/dev.webpack.config.js
  config/prod.webpack.config.js
  config/test.webpack.config.js
  locales/translations.json
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/AppEntry.js
  src/Components/AnsibleTabs/AnsibleTabs.js
  src/Components/Group/Group.js
  src/Components/Loading/Loading.js
  src/Messages.js
  src/Routes.js
  src/Routes/Register/Helpers.js
  src/Routes/Register/Register.js
Labels: :taco:, enhancement

#31 Update rhc example commands.
  src/Routes/Register/Helpers.js
Labels: :beers:, bug

#32 Update deps 🥑🥳🤙🏾
  package-lock.json
  package.json
  src/AppEntry.js
Labels: dependencies
